import fs from "node:fs";
import path from "node:path";
import {buildClaimIndex} from "./claims.js";
import {claimsListPage,claimPage} from "./claims-page.js";
const root=process.cwd(),out=path.join(root,"dist"),dirs=fs.readdirSync(path.join(root,"issues")).filter(x=>/^\d{4}$/.test(x)).sort(),registry=JSON.parse(fs.readFileSync(path.join(root,"knowledge","entities.json"),"utf8"));
const read=(p,f)=>JSON.parse(fs.readFileSync(path.join(p,f),"utf8")), bundles=dirs.map(d=>{const p=path.join(root,"issues",d);return {state:read(p,"state.json"),claims:read(p,"claims.json"),evidence:read(p,"evidence.json"),relations:read(p,"relations.json")}}),claims=buildClaimIndex(bundles,registry),byId=new Map(claims.map(c=>[c.id,c]));
const css=`:root{--paper:#F1ECE0;--ink:#292A27;--muted:#68655E;--rule:#8B877E}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}main{max-width:980px;margin:auto;padding:40px 28px 90px}.mast{border-top:8px solid;border-bottom:2px solid;padding:18px 0 12px;margin-bottom:55px}.brand{font-weight:900;font-size:clamp(42px,7vw,82px);letter-spacing:-.06em;text-align:center}.sub{text-align:center;font:700 11px monospace;letter-spacing:.22em}.nav{display:flex;gap:18px;justify-content:center;flex-wrap:wrap;margin-top:16px;font:700 11px monospace}.nav a,a{color:inherit;text-decoration:none;border-bottom:1px solid}article{max-width:760px;margin:auto}h1{font-size:54px;line-height:.95}h2{margin-top:42px;border-top:2px solid;padding-top:14px}p{font-size:18px;line-height:1.5}small{font:700 10px monospace;color:var(--muted)}.claim-row,.source,.relation{border-top:1px solid var(--rule);padding:16px 0}.claim-row h3{font-size:21px;line-height:1.35;margin:7px 0}.claim-statement{font-size:30px;line-height:1.25;font-weight:700;border-block:3px solid;padding:22px 0}.claim-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.claim-meta div{display:flex;flex-direction:column;gap:5px}@media(max-width:650px){.claim-meta{grid-template-columns:1fr 1fr}.brand{font-size:48px}}`;
const shell=(lang,body)=>`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>World System Brief · Claims</title><style>${css}</style></head><body><main><header class="mast"><div class="brand">WORLD SYSTEM BRIEF</div><div class="sub">FLOWS · BOTTLENECKS · LEVERAGE</div><nav class="nav"><a href="/${lang}/">LATEST</a><a href="/${lang}/archive/">ARCHIVE</a><a href="/${lang}/entities/">ENTITIES</a><a href="/${lang}/trajectories/">TRAJECTORIES</a><a href="/${lang}/claims/">CLAIMS</a></nav></header>${body}</main></body></html>`;
for(const lang of ["en","ua"]){const write=(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)};write(path.join(out,lang,"claims","index.html"),shell(lang,claimsListPage({lang,claims})));for(const c of claims)write(path.join(out,lang,"claim",c.id,"index.html"),shell(lang,claimPage({lang,claim:c,byId})))}
console.log(`Built ${claims.length} traceable claim pages.`);
