import fs from "node:fs";
import path from "node:path";
import { renderSystem } from "../renderer/system/system-renderer.js";
import { renderPoster } from "../renderer/poster/poster-renderer.js";
import { buildTrajectories, relationPersistence, detectTrajectoryPatterns, detectGraphTrajectoryPatterns } from "./trajectories.js";
import { trajectoriesPage } from "./trajectories-page.js";

const root=process.cwd(), out=path.join(root,"dist");
const issueDirs=fs.readdirSync(path.join(root,"issues")).filter(x=>/^\d{4}$/.test(x)).sort();
const latest=issueDirs.at(-1);
const mkdir=p=>fs.mkdirSync(p,{recursive:true});
const write=(p,s)=>{mkdir(path.dirname(p));fs.writeFileSync(p,s)};
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));
const safeUrl=s=>/^https?:\/\//i.test(String(s||""))?esc(s):"#";
function md(md){let h=esc(md).replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");return h.split(/\n\n+/).map(x=>/^<h[1-3]>/.test(x)?x:`<p>${x.replace(/\n/g,"<br>")}</p>`).join("\n")}
function shell(body,{lang="en",mode="READ",date="",issue="",archive=false,entity=false,entities=false,trajectories=false}={}){
 const other=lang==="en"?"ua":"en";
 const base=`<a href="/${lang}/">LATEST</a><a href="/${lang}/archive/">ARCHIVE</a><a href="/${lang}/entities/">ENTITIES</a><a href="/${lang}/trajectories/">TRAJECTORIES</a>`;
 const modeNav=archive||entity||entities||trajectories?`${base}<a href="/${other}/${trajectories?"trajectories/":entities||entity?"entities/":"archive/"}">${other.toUpperCase()}</a>`:`<a href="/${lang}/brief/${date}/">READ</a><a href="/${lang}/system/${date}/">SYSTEM</a><a href="/${lang}/poster/${date}/">POSTER</a>${base}<a href="/${other}/brief/${date}/">${other.toUpperCase()}</a>`;
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>World System Brief · ${esc(issue||date)}</title><style>:root{--paper:#F1ECE0;--ink:#292A27;--muted:#68655E;--rule:#8B877E}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}main{max-width:980px;margin:auto;padding:40px 28px 90px}.mast{border-top:8px solid;border-bottom:2px solid;padding:18px 0 12px;margin-bottom:55px}.brand{font-weight:900;font-size:clamp(42px,7vw,82px);letter-spacing:-.06em;text-align:center}.sub{text-align:center;font:700 11px monospace;letter-spacing:.22em}.nav{display:flex;gap:18px;justify-content:center;flex-wrap:wrap;margin-top:16px;font:700 11px monospace}.nav a,a{color:inherit;text-decoration:none;border-bottom:1px solid}article{max-width:760px;margin:auto}h1{font-size:54px;line-height:.95;letter-spacing:-.045em}h2{margin-top:48px;border-top:2px solid;padding-top:16px}p{font-size:19px;line-height:1.55}.meta{font:700 10px monospace;color:var(--muted);margin-bottom:24px}.archive-row,.entity-row{display:grid;grid-template-columns:130px 150px 1fr;gap:18px;border-top:1px solid var(--rule);padding:18px 0}.sources{margin-top:60px;border-top:3px solid;padding-top:18px}.source,.entity-event,.relation{border-top:1px solid var(--rule);padding:14px 0}.source p{font-size:14px}.entity-summary{display:grid;grid-template-columns:1fr 1fr;gap:12px;border-block:2px solid;padding:16px 0}.entity-event-grid{display:grid;grid-template-columns:120px 1fr;gap:10px 20px;margin-top:13px}.entity-k,small{font:700 10px monospace;color:var(--muted)}.entity-v{font-size:17px}.trajectory{border-top:3px solid;margin-top:42px}.trajectory h2{border:0;margin:0;padding:16px 0 5px}.trajectory .meta{margin:0 0 18px}.path{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.path span{border:1px solid;padding:10px 12px;display:flex;flex-direction:column;gap:5px}.path i{font-style:normal;font-weight:900}.relation{display:grid;grid-template-columns:1fr auto 1fr;gap:10px;align-items:baseline}.relation small{grid-column:1/-1}.relations-title{margin-top:70px}@media(max-width:650px){.archive-row,.entity-summary,.entity-row,.entity-event-grid,.relation{grid-template-columns:1fr}.brand{font-size:48px}}</style></head><body><main><header class="mast"><div class="brand">WORLD SYSTEM BRIEF</div><div class="sub">FLOWS · BOTTLENECKS · LEVERAGE</div><nav class="nav">${modeNav}</nav></header><div class="meta">${esc(issue)} · ${esc(date)} · ${esc(mode)}</div>${body}</main></body></html>`;
}
function sourcesBlock(evidence,lang){const title=lang==="ua"?"ДЖЕРЕЛА":"SOURCES";return `<section class="sources"><h2>${title}</h2>${(evidence.records||[]).map((r,i)=>`<div class="source" id="src-${esc(r.id)}"><b>[${i+1}] <a href="${safeUrl(r.url)}">${esc(r.source)}</a></b><p>${esc(r.claim||"")}</p></div>`).join("")}</section>`}
function archivePage(lang,items,lastDate){const title=lang==="ua"?"АРХІВ":"ARCHIVE";return shell(`<article><h1>${title}</h1>${items.slice().reverse().map(x=>`<div class="archive-row"><strong>${x.id}</strong><span>${x.date}</span><span><a href="/${lang}/brief/${x.date}/">READ</a> · <a href="/${lang}/system/${x.date}/">SYSTEM</a> · <a href="/${lang}/poster/${x.date}/">POSTER</a></span></div>`).join("")}</article>`,{lang,date:lastDate,issue:title,archive:true})}
function entityPage(lang,id,events){const last=events.at(-1),first=events[0],label=last.loc.labels?.[id]||id,state=x=>last.loc.states?.[x]||x||"—";const hist=events.map(e=>`<div class="entity-event"><small>${e.state.date} · ${e.state.issue_id}</small><div class="entity-event-grid"><div class="entity-k">STATE</div><div class="entity-v">${esc(state(e.object.entering_state))} → <strong>${esc(state(e.object.current_state))}</strong></div><div class="entity-k">STATUS</div><div class="entity-v">${esc(e.object.status||"—")}</div></div></div>`).join("");const records=[];for(const e of events)for(const r of e.evidence.records||[])if((r.supports||[]).includes(id)&&!records.some(x=>x.id===r.id))records.push(r);return shell(`<article><h1>${esc(label)}</h1><div class="entity-summary"><div>FIRST<br><strong>${first.state.date}</strong></div><div>CURRENT<br><strong>${esc(state(last.object.current_state))}</strong></div></div><h2>${lang==="ua"?"СИСТЕМНА БІОГРАФІЯ":"SYSTEM BIOGRAPHY"}</h2>${hist}${sourcesBlock({records},lang)}</article>`,{lang,date:last.state.date,issue:label,entity:true})}
function entitiesPage(lang,index,lastDate){const title=lang==="ua"?"СУТНОСТІ":"ENTITIES";const rows=[...index.entries()].map(([id,events])=>{const e=events.at(-1),label=e.loc.labels?.[id]||id,state=e.loc.states?.[e.object.current_state]||e.object.current_state;return {id,label,state,n:events.length}}).sort((a,b)=>a.label.localeCompare(b.label)).map(x=>`<div class="entity-row"><a href="/${lang}/entity/${encodeURIComponent(x.id)}/"><strong>${esc(x.label)}</strong></a><span>${esc(x.state)}</span><small>${x.n} ${lang==="ua"?"ВИП.":"ISSUES"}</small></div>`).join("");return shell(`<article><h1>${title}</h1>${rows}</article>`,{lang,date:lastDate,issue:title,entities:true})}

fs.rmSync(out,{recursive:true,force:true});mkdir(out);
const archive=[],entityIndex={en:new Map(),ua:new Map()},relationEvents=[],issueBundles=[];let latestLoc={};
for(const id of issueDirs){const base=path.join(root,"issues",id),state=JSON.parse(fs.readFileSync(path.join(base,"state.json"),"utf8")),ep=path.join(base,"evidence.json"),evidence=fs.existsSync(ep)?JSON.parse(fs.readFileSync(ep,"utf8")):{records:[]};archive.push({id:state.issue_id||id,date:state.date});const rp=path.join(base,"relations.json");let rj={relations:[]};if(fs.existsSync(rp)){rj=JSON.parse(fs.readFileSync(rp,"utf8"));for(const r of (rj.relations||rj.records||[]))relationEvents.push({...r,date:state.date,issue:state.issue_id||id})}issueBundles.push({state,relations:rj});
 for(const lang of ["en","ua"]){const loc=JSON.parse(fs.readFileSync(path.join(base,"locale",lang+".json"),"utf8"));latestLoc[lang]=loc;const read=fs.readFileSync(path.join(base,"read",lang+".md"),"utf8");const readPage=shell(`<article>${md(read)}${sourcesBlock(evidence,lang)}</article>`,{lang,date:state.date,issue:state.issue_id});write(path.join(out,lang,"brief",state.date,"index.html"),readPage);write(path.join(out,lang,"system",state.date,"index.html"),renderSystem(state,loc));write(path.join(out,lang,"poster",state.date,"index.html"),renderPoster(state,loc));for(const o of state.objects||[]){if(!entityIndex[lang].has(o.id))entityIndex[lang].set(o.id,[]);entityIndex[lang].get(o.id).push({state,object:o,loc,evidence})}}
}
const lastDate=archive.at(-1)?.date||"";
for(const lang of ["en","ua"]){write(path.join(out,lang,"archive","index.html"),archivePage(lang,archive,lastDate));write(path.join(out,lang,"entities","index.html"),entitiesPage(lang,entityIndex[lang],lastDate));for(const [id,events] of entityIndex[lang])write(path.join(out,lang,"entity",id,"index.html"),entityPage(lang,id,events));const ts=buildTrajectories(entityIndex[lang],relationEvents),prs=relationPersistence(relationEvents),patterns=detectTrajectoryPatterns(ts,relationEvents),graphPatterns=detectGraphTrajectoryPatterns(issueBundles),body=trajectoriesPage({lang,trajectories:ts,persistentRelations:prs,patterns,graphPatterns,labels:latestLoc[lang]?.labels||{},states:latestLoc[lang]?.states||{}});write(path.join(out,lang,"trajectories","index.html"),shell(body,{lang,date:lastDate,issue:lang==="ua"?"ТРАЄКТОРІЇ":"TRAJECTORIES",trajectories:true}));write(path.join(out,lang,"index.html"),`<!doctype html><meta http-equiv="refresh" content="0;url=/${lang}/brief/${lastDate}/">`)}
write(path.join(out,"index.html"),`<!doctype html><meta http-equiv="refresh" content="0;url=/en/brief/${lastDate}/">`);
console.log(`Built ${archive.length} issues; ${entityIndex.en.size} entities; ${buildTrajectories(entityIndex.en,relationEvents).length} trajectories; ${relationPersistence(relationEvents).length} persistent relations.`);
